import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Design System tokens (light) ─────────────────────────────────────
        'primary':                    'var(--color-primary)',
        'on-primary':                 'var(--color-on-primary)',
        'primary-container':          'var(--color-primary-container)',
        'on-primary-container':       'var(--color-on-primary-container)',
        'primary-fixed':              'var(--color-primary-fixed)',
        'primary-fixed-dim':          'var(--color-primary-fixed-dim)',
        'on-primary-fixed':           'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant':   'var(--color-on-primary-fixed-variant)',
        'inverse-primary':            'var(--color-inverse-primary)',
        'secondary':                  'var(--color-secondary)',
        'on-secondary':               'var(--color-on-secondary)',
        'secondary-container':        'var(--color-secondary-container)',
        'on-secondary-container':     'var(--color-on-secondary-container)',
        'secondary-fixed':            'var(--color-secondary-fixed)',
        'secondary-fixed-dim':        'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed':         'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'tertiary':                   'var(--color-tertiary)',
        'on-tertiary':                'var(--color-on-tertiary)',
        'tertiary-container':         'var(--color-tertiary-container)',
        'on-tertiary-container':      'var(--color-on-tertiary-container)',
        'tertiary-fixed':             'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim':         'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed':          'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant':  'var(--color-on-tertiary-fixed-variant)',
        'error':                      'var(--color-error)',
        'on-error':                   'var(--color-on-error)',
        'error-container':            'var(--color-error-container)',
        'on-error-container':         'var(--color-on-error-container)',
        'background':                 'var(--color-background)',
        'on-background':              'var(--color-on-background)',
        'surface':                    'var(--color-surface)',
        'surface-dim':                'var(--color-surface-dim)',
        'surface-bright':             'var(--color-surface-bright)',
        'surface-container-lowest':   'var(--color-surface-container-lowest)',
        'surface-container-low':      'var(--color-surface-container-low)',
        'surface-container':          'var(--color-surface-container)',
        'surface-container-high':     'var(--color-surface-container-high)',
        'surface-container-highest':  'var(--color-surface-container-highest)',
        'on-surface':                 'var(--color-on-surface)',
        'on-surface-variant':         'var(--color-on-surface-variant)',
        'inverse-surface':            'var(--color-inverse-surface)',
        'inverse-on-surface':         'var(--color-inverse-on-surface)',
        'outline':                    'var(--color-outline)',
        'outline-variant':            'var(--color-outline-variant)',
        'surface-tint':               'var(--color-surface-tint)',
        'surface-variant':            'var(--color-surface-variant)',
        // ── Tokens v2 — acento pôr-do-sol e oceano ──────────────────────────
        'accent':                     'var(--accent)',
        'accent-strong':              'var(--accent-strong)',
        'accent-soft':                'var(--accent-soft)',
        'accent-ink':                 'var(--accent-ink)',
        'ocean':                      'var(--ocean)',
        'ocean-deep':                 'var(--ocean-deep)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        card:    '20px',
        full:    '9999px',
      },
      spacing: {
        'unit-xs':             '4px',
        'unit-sm':             '8px',
        'unit-md':             '16px',
        'unit-lg':             '24px',
        'unit-xl':             '48px',
        'gutter':              '24px',
        'margin-mobile':       '16px',
        'margin-desktop':      '32px',
        'container-max-width': '1280px',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
        display: ['Nunito', 'Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg':          ['48px', { lineHeight: '56px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':         ['32px', { lineHeight: '40px',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile':  ['24px', { lineHeight: '32px',  fontWeight: '700' }],
        'headline-md':         ['24px', { lineHeight: '32px',  fontWeight: '600' }],
        'title-lg':            ['20px', { lineHeight: '28px',  fontWeight: '600' }],
        'body-lg':             ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'body-md':             ['14px', { lineHeight: '20px',  fontWeight: '400' }],
        'label-md':            ['12px', { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '600' }],
        'price-display':       ['20px', { lineHeight: '24px',  fontWeight: '700' }],
      },
      boxShadow: {
        'lift': '0px 4px 12px rgba(0,0,0,0.05)',
        'lift-md': '0px 8px 24px rgba(0,0,0,0.08)',
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
